### ISSUE TITLE
Does crash in Android 6.0.1

### ISSUE THREAD

**Issue by amilopowers** [microg/IchnaeaNlpBackend#19]
Your backend does crash in Android 6.0.1 (OmniROM and CopperheadOS).

I get no location information at all. I use a hammerhead (Nexus 5) device.

**Comment by amilopowers** [comment]
Works again. No idea why. Can be closed.

**Comment by rerbin** [comment]
The same problem on CM13.1,Nexus 5.

**Comment by amilopowers** [comment]
You need to check the permissions. It hadn't had one permission it needs.

**Comment by mar-v-in** [comment]
In v1.3.0 and UnifiedNlp v1.5.0 it should automatically ask for permission. Unfortunately both are not on F-Droid yet.

**Comment by rerbin** [comment]
Can you provide the apk file of  v1.3.0?Now i can only download the source file.

**Comment by mar-v-in** [comment]
Done.

**Comment by rerbin** [comment]
Thanks for you work.
Still crash on cm13,nexus5.I give it both location and phone permission.
Do you need  logcat info?

**Comment by mar-v-in** [comment]
Yes.

**Comment by rerbin** [comment]
03-04 16:48:45.205 D/WifiStateMachine(799): starting scan for "3lengjing"-WPA_PSK with 2462
03-04 16:48:45.325 I/E-Robot (1312): Notification posted: Notification(pri=0 contentView=com.tencent.qqpimsecure/0x7f030004 vibrate=null sound=null defaults=0x0 flags=0x62 color=0x00000000 vis=PRIVATE)
03-04 16:48:45.325 I/E-Robot (1312): Notification event posted: com.tencent.qqpimsecure: null, actions: [], extras: Bundle[{android.icon=2130837931}]
03-04 16:48:45.996 I/ActivityManager(799): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10200000 cmp=com.cyanogenmod.trebuchet/com.android.launcher3.Launcher (has extras)} from uid 1000 on display 0
03-04 16:48:46.128 I/art     (799): Background partial concurrent mark sweep GC freed 37758(2MB) AllocSpace objects, 13(300KB) LOS objects, 33% free, 25MB/38MB, paused 1.308ms total 119.932ms
03-04 16:48:46.515 D/NetlinkSocketObserver(799): NeighborEvent{elapsedMs=1001553, 192.168.1.1, [C06118FC59D9], RTM_NEWNEIGH, NUD_STALE}
03-04 16:48:46.587 W/OpenGLRenderer(1505): Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
03-04 16:48:47.754 I/E-Robot (1312): Focus change from [com.nolanlawson.logcat] -> [com.cyanogenmod.trebuchet]
03-04 16:48:48.461 I/E-Robot (1312): Alarm triggered, key: available-configured-networks-changed:poll
03-04 16:48:48.462 I/E-Robot (1312): Start wifi scan: true
03-04 16:48:48.462 I/E-Robot (1312): Reregister repeated exact alarm: available-configured-networks-changed:poll
03-04 16:48:48.462 I/E-Robot (1312): Trigger alarm "available-configured-networks-changed:poll" 1m 59s later
03-04 16:48:50.046 I/E-Robot (1312): Intent received: Intent { act=android.net.wifi.SCAN_RESULTS flg=0x4000010 (has extras) }, extras: resultsUpdated=true
03-04 16:48:50.068 I/E-Robot (1312): Available configured networks: [3lengjing, MyPC]
03-04 16:48:52.427 I/ActivityManager(799): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.google.android.gms/org.microg.nlp.ui.SettingsLauncherActivity (has extras)} from uid 10021 on display 0
03-04 16:48:52.456 I/ActivityManager(799): Start proc 7432:com.google.android.gms/u0a69 for activity com.google.android.gms/org.microg.nlp.ui.SettingsLauncherActivity
03-04 16:48:52.563 E/dex2oat (7446): Failed to create oat file: /data/dalvik-cache/arm/system@priv-app@NetworkLocation@NetworkLocation.apk@classes.dex: Permission denied
03-04 16:48:52.563 I/dex2oat (7446): dex2oat took 577.865us (threads: 4) 
03-04 16:48:52.565 W/art     (7432): Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=default --dex-file=/system/priv-app/NetworkLocation/NetworkLocation.apk --oat-file=/data/dalvik-cache/arm/system@priv-app@NetworkLocation@NetworkLocation.apk@classes.dex) because non-0 exit status
03-04 16:48:52.683 W/System  (7432): ClassLoader referenced unknown path: /system/priv-app/NetworkLocation/lib/arm
03-04 16:48:52.691 I/ActivityManager(799): START u0 {cmp=com.google.android.gms/org.microg.nlp.ui.SettingsActivity} from uid 10069 on display 0
03-04 16:48:52.891 D/OpenGLRenderer(7432): Use EGL_SWAP_BEHAVIOR_PRESERVED: true
03-04 16:48:52.933 I/Adreno-EGL(7432): <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 09/02/15, 76f806e, Ibddc658e36
03-04 16:48:52.935 I/OpenGLRenderer(7432): Initialized EGL, version 1.4
03-04 16:48:53.030 W/art     (7432): Before Android 4.1, method int android.support.v7.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
03-04 16:48:53.067 I/ActivityManager(799): Displayed com.google.android.gms/org.microg.nlp.ui.SettingsActivity: +368ms (total +626ms)
03-04 16:48:53.741 I/E-Robot (1312): Focus change from [com.cyanogenmod.trebuchet] -> [com.google.android.gms]
03-04 16:48:59.383 W/ActivityManager(799): Permission Denial: Accessing service ComponentInfo{org.microg.nlp.backend.ichnaea/org.microg.nlp.backend.ichnaea.BackendService} from pid=7432, uid=10069 requires android.permission.ACCESS_COARSE_LOCATION
03-04 16:48:59.384 D/AndroidRuntime(7432): Shutting down VM
03-04 16:48:59.386 E/AndroidRuntime(7432): FATAL EXCEPTION: main
03-04 16:48:59.386 E/AndroidRuntime(7432): Process: com.google.android.gms, PID: 7432
03-04 16:48:59.386 E/AndroidRuntime(7432): Theme: themes:{}
03-04 16:48:59.386 E/AndroidRuntime(7432): java.lang.SecurityException: Not allowed to bind to service Intent { act=org.microg.nlp.LOCATION_BACKEND pkg=org.microg.nlp.backend.ichnaea cmp=org.microg.nlp.backend.ichnaea/.BackendService }
03-04 16:48:59.386 E/AndroidRuntime(7432): 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1334)
03-04 16:48:59.386 E/AndroidRuntime(7432): 	at android.app.ContextImpl.bindService(ContextImpl.java:1298)
03-04 16:48:59.386 E/AndroidRuntime(7432): 	at android.content.ContextWrapper.bindService(ContextWrapper.java:610)
03-04 16:48:59.386 E/AndroidRuntime(7432): 	at org.microg.nlp.ui.AbstractBackendPreference.enableBackend(AbstractBackendPreference.java:208)
03-04 16:48:59.386 E/AndroidRuntime(7432): 	at org.microg.nlp.ui.AbstractBackendPreference$Adapter$1.onClick(AbstractBackendPreference.java:175)
03-04 16:48:59.386 E/AndroidRuntime(7432): 	at android.view.View.performClick(View.java:5204)
03-04 16:48:59.386 E/AndroidRuntime(7432): 	at android.widget.CompoundButton.performClick(CompoundButton.java:122)
03-04 16:48:59.386 E/AndroidRuntime(7432): 	at android.view.View$PerformClick.run(View.java:21156)
03-04 16:48:59.386 E/AndroidRuntime(7432): 	at android.os.Handler.handleCallback(Handler.java:739)
03-04 16:48:59.386 E/AndroidRuntime(7432): 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-04 16:48:59.386 E/AndroidRuntime(7432): 	at android.os.Looper.loop(Looper.java:148)
03-04 16:48:59.386 E/AndroidRuntime(7432): 	at android.app.ActivityThread.main(ActivityThread.java:5466)
03-04 16:48:59.386 E/AndroidRuntime(7432): 	at java.lang.reflect.Method.invoke(Native Method)
03-04 16:48:59.386 E/AndroidRuntime(7432): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-04 16:48:59.386 E/AndroidRuntime(7432): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
03-04 16:48:59.387 W/ActivityManager(799):   Force finishing activity com.google.android.gms/org.microg.nlp.ui.SettingsActivity
03-04 16:48:59.447 I/OpenGLRenderer(799): Initialized EGL, version 1.4
03-04 16:48:59.914 W/ActivityManager(799): Activity pause timeout for ActivityRecord{eb2a3a6 u0 com.google.android.gms/org.microg.nlp.ui.SettingsActivity t999 f}
03-04 16:49:01.376 I/Process (7432): Sending signal. PID: 7432 SIG: 9
03-04 16:49:01.400 I/WindowState(799): WIN DEATH: Window{f72e1fb u0 com.google.android.gms/org.microg.nlp.ui.SettingsActivity}
03-04 16:49:01.400 D/GraphicsStats(799): Buffer count: 6
03-04 16:49:01.405 I/WindowState(799): WIN DEATH: Window{6976739 u0 com.google.android.gms/org.microg.nlp.ui.SettingsActivity}
03-04 16:49:01.435 I/ActivityManager(799): Process com.google.android.gms (pid 7432) has died
03-04 16:49:01.572 W/AppOps  (799): Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
03-04 16:49:01.750 I/E-Robot (1312): Focus change from [com.google.android.gms] -> [com.cyanogenmod.trebuchet]
03-04 16:49:03.115 I/ActivityManager(799): START u0 {act=com.android.systemui.recents.SHOW_RECENTS flg=0x10804000 cmp=com.android.systemui/.recents.RecentsActivity} from uid 10018 on display 0
03-04 16:49:03.746 I/E-Robot (1312): Focus change from [com.cyanogenmod.trebuchet] -> [com.android.systemui]
03-04 16:49:04.608 V/PhoneStatusBar(953): setLightsOn(true)
03-04 16:49:04.832 V/PhoneStatusBar(953): setLightsOn(true)
03-04 16:49:05.207 D/WifiStateMachine(799): starting scan for "3lengjing"-WPA_PSK with 2462
03-04 16:49:05.755 I/E-Robot (1312): Focus change from [com.android.systemui] -> [com.nolanlawson.logcat]

**Comment by mar-v-in** [comment]
The crash seems not to be caused by the Mozilla backend. Did you grant location permission to UnifiedNlp?

**Comment by rerbin** [comment]
![screenshot_20160304-170010](https://cloud.githubusercontent.com/assets/17610552/13522486/e7a822b8-e22a-11e5-8668-a5c0b30f6337.png)

**Comment by mar-v-in** [comment]
Did you install NetworkLocation.apk to /system/priv-app (or using a /system mover tool)? This is not intended for systems >4.4. It should work as a "usual" app.

**Comment by rerbin** [comment]
yes,i  install NetworkLocation.apk to /system/priv-app

**Comment by mar-v-in** [comment]
Try to install it as a normal app (remove it from /system/priv-app first).

**Comment by rerbin** [comment]
when install it as a normal app, it doesn't  appear in Location-Location services.
when  install NetworkLocation.apk to /system/priv-app,it   appear in Location-Location services.

**Comment by mar-v-in** [comment]
It's not necessary to appear as Location service for functionality. The settings will pop-up as a normal app when it's not in Location->Location services.

**Comment by rerbin** [comment]
install it as a normal app still crash

**Comment by mar-v-in** [comment]
try untick/tick location permission for UnifiedNlp, reboot and provide new logcat if problem persists.

**Comment by rerbin** [comment]
![screenshot_20160304-183936](https://cloud.githubusercontent.com/assets/17610552/13524977/4eecf026-e239-11e5-95c6-80ed6a94b8c3.png)

**Comment by mar-v-in** [comment]
Can you try running in a root shell `pm grant com.google.android.gms android.permission.ACCESS_COARSE_LOCATION`

**Comment by mar-v-in** [comment]
Please continue further discussion on this problem in https://github.com/microg/android_packages_apps_UnifiedNlp/issues/68 where it really belongs. Will close here.
